version: "4.5"
services:
    nopcommerce_web:
        image: "nopcommerceteam/nopcommerce:4.50.4"
        container_name: hci_nopcommerce
        ports:
            - "80:80"
        depends_on:
            - hci_db
        volumes:
            - web_plugins:/app/Plugins
            - web_themes:/app/Themes
            - web_content:/app/wwwroot
    hci_db:
        image: "mysql:8.0"
        container_name: hci_nopcommerce_mysql_server
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "test123"
            MYSQL_DATABASE: hci_db
            MYSQL_USER: hci_admin_db
            MYSQL_PASSWORD: "test123456"
        ports:
            - "6033:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
  web_plugins:
  web_themes:
  web_content:
  db_data:
